const lang = {
    en: {
        // Navigation
        homeNav: "Home",
        aboutNav: "About",
        contactNav: "Contact",
        propertiesNav: "Properties",
        langbtn: '🌐 Language <i class="fa-solid fa-caret-down"></i>',
        
        // Home Page - Hero
        heroTitle: "Find Your Dream Home",
        heroDesc: "Safe and suitable properties for you.",
        heroBtn: "View Properties",
        
        // Home Page - Recommended Properties
        recommendedTitle: "Recommended Properties",
        property1Title: "Modern Apartment",
        property1Location: "Tirana, Albania",
        property2Title: "Luxury Villa",
        property2Location: "Durres, Albania",
        property3Title: "Cozy Apartment",
        property3Location: "Vlore, Albania",
        
        // Home Page - Why Choose Us
        whyTitle: "Why Choose Us",
        why1Title: "Safe Properties",
        why1Desc: "Complete verification of documents and owners.",
        why2Title: "Professional Support",
        why2Desc: "Our team is always ready to help.",
        why3Title: "Tailored for You",
        why3Desc: "Search and find properties that match your needs.",
        
        // Properties Page
        propertiesPageTitle: "Discover Your Ideal Property",
        propertiesPageDesc: "More than 500 properties available across Albania",
        filterLocation: "Location",
        filterType: "Type",
        filterPrice: "Price",
        filterBtn: "Search",
        filterTitle: "Advanced Filters",
        typeApartment: "Apartment",
        typeVilla: "Villa",
        typeHouse: "House",
        noResults: "No properties found.",
        prop1Title: "Modern Downtown Apartment",
        prop1Location: "Tirana, Blloku",
        prop2Title: "Luxury Villa with Sea View",
        prop2Location: "Durres, Beach",
        prop3Title: "Cozy Family Apartment",
        prop3Location: "Vlore, Lungomare",
        prop4Title: "House with Large Garden",
        prop4Location: "Tirana, Kashar",
        prop5Title: "Hillside Villa with Pool",
        prop5Location: "Tirana, Dajti",
        prop6Title: "Penthouse with Panorama",
        prop6Location: "Tirana, Center",
        prop1Desc1: "This modern downtown apartment is located in Tirana's trendy Blloku neighborhood with bright interiors and contemporary design.",
        prop1Desc2: "Fully renovated with elevator access and close to restaurants, shops, and cultural attractions.",
        prop2Desc1: "Luxury villa offering breathtaking sea views, infinity pool, and premium finishes in Durres Beach.",
        prop2Desc2: "Designed for entertaining with landscaped garden, home gym, and smart home features.",
        prop3Desc1: "Cozy family apartment along Vlore Lungomare with sea view and beach access.",
        prop3Desc2: "Modern kitchen, smart amenities, and perfect for relaxed seaside living.",
        prop4Desc1: "Spacious house in Kashar with a large 800m² garden and family-friendly layout.",
        prop4Desc2: "Features modern kitchen, fireplace, parking, and ample outdoor space for gatherings.",
        prop5Desc1: "Hillside villa in Dajti with resort-style pool and panoramic mountain views.",
        prop5Desc2: "Luxury amenities include spa area, wine cellar, smart home, and landscaped gardens.",
        prop6Desc1: "Prestigious penthouse with 360° skyline views in the center of Tirana.",
        prop6Desc2: "Floor-to-ceiling windows, expansive terrace, and concierge services for premium city living.",
        viewDetails: "View Details",
        
        // About Page
        aboutHeroTitle: "About HomeSpace",
        aboutHeroDesc: "Our mission is to make finding your dream home simple, safe, and reliable.",
        storyTitle: "Our Story",
        storyP1: "HomeSpace was founded in 2020 with a simple vision: to revolutionize the real estate market in Albania. We understood that the process of buying or renting a property was often complicated, unreliable, and full of challenges.",
        storyP2: "Our team arose from the need to create a modern platform where transparency, trust, and professionalism are at the center of every transaction. Thanks to modern technology and a dedicated team of professionals, we have helped thousands of families and individuals find their ideal home.",
        storyP3: "Today, HomeSpace is one of the most trusted real estate platforms in Albania, with over 500 active properties and a network of partners across the country.",
        statProperties: "Active Properties",
        statClients: "Satisfied Clients",
        statPartners: "Partners",
        statYears: "Years Experience",
        valuesTitle: "Our Values",
        value1Title: "Safety & Trust",
        value1Desc: "Every property is carefully verified to guarantee complete safety for you.",
        value2Title: "Transparency",
        value2Desc: "Complete and clear information for every property detail.",
        value3Title: "Dedication",
        value3Desc: "Our team works every day to find the perfect solution for you.",
        value4Title: "Innovation",
        value4Desc: "Modern technology for a better search experience.",
        teamTitle: "Our Team",
        roleFounder: "Founder & CEO",
        roleSales: "Sales Director",
        roleTech: "Technology Director",
        teamDesc1: "The vision and leadership behind the HomeSpace platform.",
        teamDesc2: "Real estate expert with 10 years of experience.",
        teamDesc3: "Platform developer and technological innovations.",
        
        // Contact Page
        contactHeroTitle: "Contact Us",
        contactHeroDesc: "We're here to help. Don't hesitate to contact us!",
        contactInfoTitle: "Contact Information",
        addressTitle: "Address",
        addressContent: "Myslym Shyri Street, No. 42<br>Tirana, Albania 1001",
        phoneTitle: "Phone",
        emailTitle: "Email",
        hoursTitle: "Working Hours",
        hoursContent: "Monday - Friday: 09:00 - 18:00<br>Saturday: 09:00 - 14:00<br>Sunday: Closed",
        socialTitle: "Follow Us",
        formTitle: "Send a Message",
        successMsg: "Your message was sent successfully! We'll contact you soon.",
        nameLabel: "Full Name *",
        emailLabel: "Email *",
        phoneLabel: "Phone",
        subjectLabel: "Subject",
        subjectGeneral: "General Question",
        subjectProperty: "Property Question",
        subjectAppointment: "Appointment Request",
        subjectOther: "Other",
        messageLabel: "Message *",
        submitBtn: "Send Message",
        
        // Footer
        // Property Detail Pages
        backToProperties: "Back to Properties",
        bedrooms: "Bedrooms",
        bathrooms: "Bathrooms",
        floorArea: "Floor Area",
        aboutThisProperty: "About This Property",
        amenities: "Amenities",
        additionalInfo: "Additional Information",
        contactAgent: "Contact Agent",
        propertyType: "Property Type",
        builtYear: "Built Year",
        condition: "Condition",
        heating: "Heating",
        excellent: "Excellent",
        underfloor: "Underfloor Heating",
        central: "Central",
        topFloor: "Top Floor",
        penthouse: "Penthouse",
        agentMessage: "We will contact you soon after your message.",
        highSpeedInternet: "High-Speed Internet",
        airConditioning: "Air Conditioning",
        elevatorAccess: "Elevator Access",
        parkingSpace: "Parking Space",
        security: "Security",
        gymAccess: "Gym Access",
        terrace: "Terrace",
        greenArea: "Green Area",
        privateBeachAccess: "Private Beach Access",
        infinityPool: "Infinity Pool",
        landscapedGarden: "Landscaped Garden",
        jacuzzi: "Jacuzzi",
        homeGym: "Home Gym",
        wineCellar: "Wine Cellar",
        outdoorLounge: "Outdoor Lounge",
        smartHome: "Smart Home",
        seaView: "Sea View",
        beachAccess: "Beach Access",
        modernKitchen: "Modern Kitchen",
        wifi: "WiFi",
        smartTV: "Smart TV",
        balconyTerrace: "Balcony Terrace",
        largeGarden: "Large Garden",
        fruitTrees: "Fruit Trees",
        spaciousRooms: "Spacious Rooms",
        fireplace: "Fireplace",
        internetReady: "Internet Ready",
        resortPool: "Resort Pool",
        panoramicViews: "Panoramic Views",
        spaArea: "Spa Area",
        securitySystem: "Security System",
        rooftopTerrace: "Rooftop Terrace",
        concierge: "Concierge",
        privateElevator: "Private Elevator",
        privateSpa: "Private Spa",
        wineBar: "Wine Bar",
        fullSmartHome: "Full Smart Home",
        security247: "24/7 Security",
        
        // Footer
        footerTitle: "HomeSpace",
        footerDesc: "Modern platform for properties and apartments.",
        footerSocialTitle: "Social Media",
        footerInstagram: "Instagram: example_22",
        footerLinkedIn: "LinkedIn: example.com",
        footerContactTitle: "Contact",
        footerEmail: "Email: info@homespace.com",
        footerPhone: "Phone: +355 67 000 0000",
        footerBottom: "© 2025 HomeSpace — All rights reserved."
    },
    al: {
        // Navigation
        homeNav: "Kryefaqja",
        aboutNav: "Rreth Nesh",
        contactNav: "Kontakti",
        propertiesNav: "Pronat",
        langbtn: '🌐 Gjuha <i class="fa-solid fa-caret-down"></i>',
        
        // Home Page - Hero
        heroTitle: "Gjej Shtepine e Enderrave",
        heroDesc: "Prona të sigurta dhe të përshtatura për ty.",
        heroBtn: "Shiko Prona",
        
        // Home Page - Recommended Properties
        recommendedTitle: "Prona të Rekomanduara",
        property1Title: "Banese Moderne",
        property1Location: "Tiranë, Shqipëri",
        property2Title: "Vilë Luksoze",
        property2Location: "Durrës, Shqipëri",
        property3Title: "Apartament Komod",
        property3Location: "Vlorë, Shqipëri",
        
        // Home Page - Why Choose Us
        whyTitle: "Pse të na Zgjidhni",
        why1Title: "Prona të Sigurta",
        why1Desc: "Verifikim i plotë i dokumentacionit dhe pronarëve.",
        why2Title: "Mbështetje Profesionale",
        why2Desc: "Ekipi ynë është gjithmonë gati për të ndihmuar.",
        why3Title: "Përshtatje për Ju",
        why3Desc: "Kërkoni dhe gjeni prona që përputhen me nevojat tuaja.",
        
        // Properties Page
        propertiesPageTitle: "Zbuloni Pronën Tuaj Ideale",
        propertiesPageDesc: "Më shumë se 500 prona në dispozicion në të gjithë Shqipërinë",
        filterLocation: "Lokacioni",
        filterType: "Tipi",
        filterPrice: "Çmimi",
        filterBtn: "Kërko",
        filterTitle: "Filtra Avancuar",
        typeApartment: "Apartament",
        typeVilla: "Vilë",
        typeHouse: "Shtëpi",
        noResults: "Nuk u gjetën prona.",
        prop1Title: "Apartament Modern në Qendër",
        prop1Location: "Tiranë, Blloku",
        prop2Title: "Vilë Luksoze me Pamje Deti",
        prop2Location: "Durrës, Plazh",
        prop3Title: "Apartament Komod Familjar",
        prop3Location: "Vlorë, Lungomare",
        prop4Title: "Shtëpi me Oborr të Madh",
        prop4Location: "Tiranë, Kashar",
        prop5Title: "Vilë me Pishinë në Kodër",
        prop5Location: "Tiranë, Dajti",
        prop6Title: "Penthouse me Panoramë",
        prop6Location: "Tiranë, Qendër",
        prop1Desc1: "Ky apartament modern në qendër ndodhet në lagjen trendi Blloku me ambiente të ndriçuara dhe dizajn bashkëkohor.",
        prop1Desc2: "Totalisht i rinovuar me ashensor dhe pranë restoranteve, dyqaneve dhe atraksioneve kulturore.",
        prop2Desc1: "Vilë luksoze me pamje mahnitëse deti, pishinë infinity dhe përfundime premium në Plazhin e Durrësit.",
        prop2Desc2: "Projektuar për mikpritje me kopsht të kuruar, palestër në shtëpi dhe veçori smart home.",
        prop3Desc1: "Apartament komod familjar përgjatë Lungomares në Vlorë me pamje deti dhe akses në plazh.",
        prop3Desc2: "Kuzhinë moderne, pajisje smart dhe i përsosur për jetesë të qetë buzë detit.",
        prop4Desc1: "Shtëpi e gjerë në Kashar me një oborr të madh 800m² dhe planimetri familjare.",
        prop4Desc2: "Përfshin kuzhinë moderne, oxhak, parkim dhe hapësirë të bollshme të jashtme për mbledhje.",
        prop5Desc1: "Vilë në kodrat e Dajtit me pishinë resorti dhe pamje panoramike nga mali.",
        prop5Desc2: "Amenitete luksoze si zonë spa, bodrum vere, smart home dhe kopshte të kuruara.",
        prop6Desc1: "Penthouse prestigjioze me pamje 360° të skyline në qendër të Tiranës.",
        prop6Desc2: "Dritare deri në dysheme, tarracë e gjerë dhe concierge për jetesë premium urbane.",
        viewDetails: "Shiko Detajet",
        
        // About Page
        aboutHeroTitle: "Rreth HomeSpace",
        aboutHeroDesc: "Misioni ynë është të bëjmë gjetjen e shtëpisë së ëndrrave tuaja të thjeshtë, të sigurt dhe të besueshme.",
        storyTitle: "Historia Jonë",
        storyP1: "HomeSpace u themelua në vitin 2020 me një vizion të thjeshtë: të revolucionarizojmë tregun e pasurive të paluajtshme në Shqipëri. Ne kuptuam se procesi i blerjes ose dhënies me qera të një prone shpesh ishte i komplikuar, i pabesueshëm dhe i mbushur me sfida.",
        storyP2: "Ekipi ynë u ngrit nga nevoja për të krijuar një platformë moderne ku transparenca, besimi dhe profesionalizmi janë në qendër të çdo transaksioni. Falë teknologjisë moderne dhe një ekipi të dedikuar profesionistësh, ne kemi ndihmuar mijëra familje dhe individë të gjejnë shtëpinë e tyre ideale.",
        storyP3: "Sot, HomeSpace është një nga platformat më të besueshme të pasurive të paluajtshme në Shqipëri, me mbi 500 prona aktive dhe një rrjet partnerësh në të gjithë vendin.",
        statProperties: "Prona Aktive",
        statClients: "Klientë të Kënaqur",
        statPartners: "Partnerë",
        statYears: "Vite Eksperiencë",
        valuesTitle: "Vlerat Tona",
        value1Title: "Siguri & Besim",
        value1Desc: "Çdo pronë verifikohet me kujdes për të garantuar siguri të plotë për ju.",
        value2Title: "Transparencë",
        value2Desc: "Informacion i plotë dhe i qartë për çdo detaj të pronës.",
        value3Title: "Përkushtim",
        value3Desc: "Ekipi ynë punon çdo ditë për të gjetur zgjidhjen perfekte për ju.",
        value4Title: "Inovacion",
        value4Desc: "Teknologji moderne për një përvojë më të mirë kërkimi.",
        teamTitle: "Ekipi Ynë",
        roleFounder: "Themelues & CEO",
        roleSales: "Drejtore Shitjesh",
        roleTech: "Drejtor Teknologjik",
        teamDesc1: "Vizioni dhe udhëheqësi pas platformës HomeSpace.",
        teamDesc2: "Eksperte në pasuritë e paluajtshme me 10 vjet eksperiencë.",
        teamDesc3: "Zhvillues platformës dhe inovacioneve teknologjike.",
        
        // Contact Page
        contactHeroTitle: "Na Kontaktoni",
        contactHeroDesc: "Jemi këtu për t'ju ndihmuar. Mos hezitoni të na kontaktoni!",
        contactInfoTitle: "Informacion Kontakti",
        addressTitle: "Adresa",
        addressContent: "Rruga Myslym Shyri, Nr. 42<br>Tiranë, Shqipëri 1001",
        phoneTitle: "Telefon",
        emailTitle: "Email",
        hoursTitle: "Orari i Punës",
        hoursContent: "E Hënë - E Premte: 09:00 - 18:00<br>E Shtunë: 09:00 - 14:00<br>E Diel: Mbyllur",
        socialTitle: "Na Ndiqni",
        formTitle: "Dërgoni një Mesazh",
        successMsg: "Mesazhi juaj u dërgua me sukses! Do t'ju kontaktojmë së shpejti.",
        nameLabel: "Emri dhe Mbiemri *",
        emailLabel: "Email *",
        phoneLabel: "Telefon",
        subjectLabel: "Subjekti",
        subjectGeneral: "Pyetje e Përgjithshme",
        subjectProperty: "Pyetje për Pronë",
        subjectAppointment: "Kërkesë për Takim",
        subjectOther: "Tjetër",
        messageLabel: "Mesazhi *",
        submitBtn: "Dërgo Mesazhin",
        
        // Footer
        // Property Detail Pages
        backToProperties: "Kthehu te Pronat",
        bedrooms: "Dhoma Gjumi",
        bathrooms: "Banja",
        floorArea: "Sipërfaqja e Dyshemesë",
        aboutThisProperty: "Rreth Kësaj Prone",
        amenities: "Amenitetet",
        additionalInfo: "Informacion i Shtesë",
        contactAgent: "Kontakto Agjentin",
        propertyType: "Lloji i Pronës",
        builtYear: "Viti i Ndërtimit",
        condition: "Kushti",
        heating: "Ngrohje",
        excellent: "Ekselente",
        underfloor: "Ngrohje Nën Dysheme",
        central: "Qendrore",
        topFloor: "Kati i Sipërm",
        penthouse: "Penthouse",
        agentMessage: "Do t'ju kontaktojmë shpejt pas mesazhit tuaj.",
        highSpeedInternet: "Internet me Shpejtësi të Lartë",
        airConditioning: "Ajrim Kondicionuar",
        elevatorAccess: "Akses me Ashensor",
        parkingSpace: "Hapësirë Parkimi",
        security: "Siguri",
        gymAccess: "Qasje në Palestër",
        terrace: "Terracë",
        greenArea: "Zonë e Gjelbër",
        privateBeachAccess: "Akses Privat në Plazh",
        infinityPool: "Pishinë Infinity",
        landscapedGarden: "Oborr i Kuruar",
        jacuzzi: "Jacuzzi",
        homeGym: "Palestër në Shtëpi",
        wineCellar: "Bodrum Vini",
        outdoorLounge: "Sallë Jashtë",
        smartHome: "Shtëpi Smart",
        seaView: "Pamje Deti",
        beachAccess: "Akses në Plazh",
        modernKitchen: "Kuzhinë Moderne",
        wifi: "WiFi",
        smartTV: "TV Smart",
        balconyTerrace: "Balkon-Terracë",
        largeGarden: "Oborr i Madh",
        fruitTrees: "Pemë Frutash",
        spaciousRooms: "Dhoma të Gjera",
        fireplace: "Oxhak",
        internetReady: "Gati për Internet",
        resortPool: "Pishinë Resorti",
        panoramicViews: "Pamje Panoramike",
        spaArea: "Zonë Spa",
        securitySystem: "Sistem Siguri",
        rooftopTerrace: "Terracë mbi Çat",
        concierge: "Concierge",
        privateElevator: "Ashensor Privat",
        privateSpa: "Spa Private",
        wineBar: "Bar Vini",
        fullSmartHome: "Smart Home i Plotë",
        security247: "Siguri 24/7",
        
        // Footer
        footerTitle: "HomeSpace",
        footerDesc: "Platformë moderne për prona dhe banesa.",
        footerSocialTitle: "Rrjetet Sociale",
        footerInstagram: "Instagram: example_22",
        footerLinkedIn: "LinkedIn: example.com",
        footerContactTitle: "Kontakt",
        footerEmail: "Email: info@homespace.com",
        footerPhone: "Tel: +355 67 000 0000",
        footerBottom: "© 2025 HomeSpace — Të gjitha të drejtat e rezervuara."
    }
};